// Transparency notices and data subject requests — 009_API_SURFACE section 11.
//
// Routes:
//   GET  /v1/transparency-notices                         — authenticated user's notices
//   GET  /v1/transparency-notices/:noticeId               — single notice
//   POST /v1/transparency-notices/:noticeId/acknowledge   — mark acknowledged_at
//   GET  /v1/data-subject-requests                        — IO sees all; user sees own
//   POST /v1/data-subject-requests                        — data subject submits request
//   GET  /v1/data-subject-requests/:dsrId                 — single DSR
//   PATCH /v1/data-subject-requests/:dsrId                — IO resolves/transitions
//
// Transparency notices are generated by other services (bheka-notify, bheka-case)
// reacting to tier activations, policy changes, and conclusions (CANON section 5,
// 018_NOTIFICATIONS_AND_TRANSPARENCY). The gateway exposes read + acknowledge only.
//
// Data subject requests are POPIA ss23-25 rights requests (access, correction,
// objection, deletion). Any authenticated user may submit for themselves.
// The Information Officer resolves requests via PATCH.

import { Router, type IRouter } from "express";
import { uuidv7 } from "uuidv7";
import { publishEvent } from "@workspace/nats-client";
import { z } from "zod";
import { and, eq, gt, inArray } from "drizzle-orm";
import {
  db,
  transparencyNoticesTable,
  dataSubjectRequestsTable,
  roleAssignmentsTable,
  rolesTable,
} from "@workspace/db";
import { withTenantContext } from "../../lib/tenant-context.js";
import { writeAuditLog } from "../../lib/audit-writer.js";
import { sendProblem, Problems } from "../../lib/problem.js";
import { requireSession } from "../../middleware/require-session.js";
import { requireRole } from "../../middleware/require-role.js";

// Returns true if the given user holds any elevated role within the tenant.
// "Elevated" here means: can see all notices / DSRs in the tenant, not just their own.
async function hasElevatedRole(userId: string, tenantId: string): Promise<boolean> {
  const assignments = await withTenantContext(tenantId, (tx) =>
    tx
      .select({ id: roleAssignmentsTable.id })
      .from(roleAssignmentsTable)
      .innerJoin(rolesTable, eq(roleAssignmentsTable.roleId, rolesTable.id))
      .where(
        and(
          eq(roleAssignmentsTable.userId, userId),
          eq(roleAssignmentsTable.tenantId, tenantId),
          eq(roleAssignmentsTable.active, true),
          inArray(rolesTable.name, ["popia_information_officer", "security_administrator"]),
        ),
      )
      .limit(1),
  );
  return assignments.length > 0;
}

const router: IRouter = Router();

// ── GET /v1/transparency-notices ─────────────────────────────────────────────
// Returns notices for the authenticated user.
// IO and security_administrator may see all notices for the tenant via ?all=true.

router.get(
  "/v1/transparency-notices",
  requireSession,
  async (req, res): Promise<void> => {
    const tenantId = req.session!.tenantId;
    const userId = req.session!.userId;
    const allTenant = req.query.all === "true";
    const rawLimit = Number(req.query.limit ?? 50);
    const limit = Math.min(Math.max(1, rawLimit), 200);
    const cursor = req.query.cursor as string | undefined;

    const canSeeAll =
      allTenant && (await hasElevatedRole(req.session!.userId, tenantId));

    const rows = await withTenantContext(tenantId, (tx) =>
      tx
        .select()
        .from(transparencyNoticesTable)
        .where(
          and(
            eq(transparencyNoticesTable.tenantId, tenantId),
            canSeeAll ? undefined : eq(transparencyNoticesTable.userId, userId),
            cursor ? gt(transparencyNoticesTable.id, cursor) : undefined,
          ),
        )
        .orderBy(transparencyNoticesTable.id)
        .limit(limit + 1),
    );

    const hasMore = rows.length > limit;
    const items = hasMore ? rows.slice(0, limit) : rows;
    const nextCursor = hasMore ? items[items.length - 1]!.id : null;

    res.json({
      items: items.map((n) => ({
        id: n.id,
        userId: n.userId,
        noticeType: n.noticeType,
        title: n.title,
        body: n.body,
        language: n.language,
        issuedAt: n.issuedAt,
        acknowledgedAt: n.acknowledgedAt,
        createdAt: n.createdAt,
      })),
      pageInfo: { nextCursor, hasMore },
    });
  },
);

// ── GET /v1/transparency-notices/:noticeId ───────────────────────────────────

router.get(
  "/v1/transparency-notices/:noticeId",
  requireSession,
  async (req, res): Promise<void> => {
    const tenantId = req.session!.tenantId;
    const userId = req.session!.userId;
    const noticeId = req.params.noticeId as string;

    const isElevated = await hasElevatedRole(userId, tenantId);

    const [notice] = await withTenantContext(tenantId, (tx) =>
      tx
        .select()
        .from(transparencyNoticesTable)
        .where(
          and(
            eq(transparencyNoticesTable.id, noticeId),
            eq(transparencyNoticesTable.tenantId, tenantId),
            isElevated ? undefined : eq(transparencyNoticesTable.userId, userId),
          ),
        )
        .limit(1),
    );

    if (!notice) {
      sendProblem(res, Problems.notFound());
      return;
    }

    res.json({
      id: notice.id,
      tenantId: notice.tenantId,
      userId: notice.userId,
      noticeType: notice.noticeType,
      title: notice.title,
      body: notice.body,
      language: notice.language,
      issuedAt: notice.issuedAt,
      acknowledgedAt: notice.acknowledgedAt,
      createdAt: notice.createdAt,
      updatedAt: notice.updatedAt,
    });
  },
);

// ── POST /v1/transparency-notices/:noticeId/acknowledge ──────────────────────
// Data subject acknowledges receipt. Idempotent: second call is a no-op.

router.post(
  "/v1/transparency-notices/:noticeId/acknowledge",
  requireSession,
  async (req, res): Promise<void> => {
    const tenantId = req.session!.tenantId;
    const userId = req.session!.userId;
    const noticeId = req.params.noticeId as string;

    const [notice] = await withTenantContext(tenantId, (tx) =>
      tx
        .select()
        .from(transparencyNoticesTable)
        .where(
          and(
            eq(transparencyNoticesTable.id, noticeId),
            eq(transparencyNoticesTable.tenantId, tenantId),
            eq(transparencyNoticesTable.userId, userId),
          ),
        )
        .limit(1),
    );

    if (!notice) {
      sendProblem(res, Problems.notFound());
      return;
    }

    // Idempotent: already acknowledged.
    if (notice.acknowledgedAt) {
      res.json({
        id: notice.id,
        acknowledgedAt: notice.acknowledgedAt,
      });
      return;
    }

    const now = new Date();
    const [updated] = await withTenantContext(tenantId, (tx) =>
      tx
        .update(transparencyNoticesTable)
        .set({ acknowledgedAt: now, updatedAt: now })
        .where(
          and(
            eq(transparencyNoticesTable.id, noticeId),
            eq(transparencyNoticesTable.tenantId, tenantId),
          ),
        )
        .returning({ id: transparencyNoticesTable.id, acknowledgedAt: transparencyNoticesTable.acknowledgedAt }),
    );

    res.json({
      id: updated!.id,
      acknowledgedAt: updated!.acknowledgedAt,
    });
  },
);

// ── GET /v1/data-subject-requests ────────────────────────────────────────────
// IO / security_administrator: all DSRs for the tenant.
// Other authenticated users: only their own requests.

router.get(
  "/v1/data-subject-requests",
  requireSession,
  async (req, res): Promise<void> => {
    const tenantId = req.session!.tenantId;
    const userId = req.session!.userId;
    const rawLimit = Number(req.query.limit ?? 50);
    const limit = Math.min(Math.max(1, rawLimit), 200);
    const cursor = req.query.cursor as string | undefined;

    const isElevated = await hasElevatedRole(userId, tenantId);

    const rows = await withTenantContext(tenantId, (tx) =>
      tx
        .select()
        .from(dataSubjectRequestsTable)
        .where(
          and(
            eq(dataSubjectRequestsTable.tenantId, tenantId),
            isElevated ? undefined : eq(dataSubjectRequestsTable.userId, userId),
            cursor ? gt(dataSubjectRequestsTable.id, cursor) : undefined,
          ),
        )
        .orderBy(dataSubjectRequestsTable.id)
        .limit(limit + 1),
    );

    const hasMore = rows.length > limit;
    const items = hasMore ? rows.slice(0, limit) : rows;
    const nextCursor = hasMore ? items[items.length - 1]!.id : null;

    res.json({
      items: items.map((d) => ({
        id: d.id,
        userId: d.userId,
        requestType: d.requestType,
        status: d.status,
        requestDetails: d.requestDetails,
        resolutionNotes: isElevated ? d.resolutionNotes : undefined,
        resolvedAt: d.resolvedAt,
        createdAt: d.createdAt,
        updatedAt: d.updatedAt,
      })),
      pageInfo: { nextCursor, hasMore },
    });
  },
);

// ── POST /v1/data-subject-requests ───────────────────────────────────────────
// Any authenticated user may submit a DSR for themselves (POPIA ss23-25).

const CreateDsrBody = z.object({
  requestType: z.enum(["access", "correction", "objection", "deletion"]),
  requestDetails: z.string().max(4000).optional(),
});

router.post(
  "/v1/data-subject-requests",
  requireSession,
  async (req, res): Promise<void> => {
    const tenantId = req.session!.tenantId;
    const userId = req.session!.userId;

    const idempotencyKey = req.headers["idempotency-key"];
    if (!idempotencyKey) {
      sendProblem(res, Problems.idempotencyKeyRequired());
      return;
    }

    const parsed = CreateDsrBody.safeParse(req.body);
    if (!parsed.success) {
      sendProblem(res, Problems.validationFailed(
        parsed.error.message,
        parsed.error.issues.map((i) => ({ field: i.path.join("."), code: i.code, message: i.message })),
      ));
      return;
    }

    const [dsr] = await withTenantContext(tenantId, (tx) =>
      tx
        .insert(dataSubjectRequestsTable)
        .values({ tenantId, userId, ...parsed.data })
        .returning(),
    );

    await writeAuditLog({
      tenantId,
      actorId: userId,
      actorType: "user",
      action: "dsr.submitted",
      targetType: "data_subject_request",
      targetId: dsr!.id,
      requestId: String(idempotencyKey),
      metadata: { requestType: parsed.data.requestType },
    });

    // For deletion requests: create a receipt notice for the data subject and
    // emit bheka.notice.issued.v1 so bheka-notify can deliver it.
    // Other DSR types (access, correction, objection) are handled by the IO manually.
    if (parsed.data.requestType === "deletion") {
      const [notice] = await withTenantContext(tenantId, (tx) =>
        tx.insert(transparencyNoticesTable).values({
          tenantId,
          userId,
          noticeType: "data_subject_request_response",
          title: "Data Erasure Request Received",
          body: `Your request to erase your personal data has been received (reference: ${dsr!.id}). We will process your request within 21 days as required by POPIA.`,
          language: "en",
        }).returning(),
      );

      await publishEvent({
        event_id: uuidv7(),
        schema_version: "bheka.notice.issued.v1",
        occurred_at: new Date().toISOString(),
        producer: "bheka-case",
        data: {
          notice_id: notice!.id,
          tenant_id: tenantId,
          user_id: userId,
          notice_type: "data_subject_request_response",
          language: "en",
          issued_at: new Date().toISOString(),
          delivery_channels: ["in_app"],
        },
      });
    }

    res.status(201).json({
      id: dsr!.id,
      userId: dsr!.userId,
      requestType: dsr!.requestType,
      status: dsr!.status,
      requestDetails: dsr!.requestDetails,
      createdAt: dsr!.createdAt,
    });
  },
);

// ── GET /v1/data-subject-requests/:dsrId ────────────────────────────────────

router.get(
  "/v1/data-subject-requests/:dsrId",
  requireSession,
  async (req, res): Promise<void> => {
    const tenantId = req.session!.tenantId;
    const userId = req.session!.userId;
    const dsrId = req.params.dsrId as string;

    const isElevated = await hasElevatedRole(userId, tenantId);

    const [dsr] = await withTenantContext(tenantId, (tx) =>
      tx
        .select()
        .from(dataSubjectRequestsTable)
        .where(
          and(
            eq(dataSubjectRequestsTable.id, dsrId),
            eq(dataSubjectRequestsTable.tenantId, tenantId),
            isElevated ? undefined : eq(dataSubjectRequestsTable.userId, userId),
          ),
        )
        .limit(1),
    );

    if (!dsr) {
      sendProblem(res, Problems.notFound());
      return;
    }

    res.json({
      id: dsr.id,
      tenantId: dsr.tenantId,
      userId: dsr.userId,
      requestType: dsr.requestType,
      status: dsr.status,
      requestDetails: dsr.requestDetails,
      resolutionNotes: dsr.resolutionNotes,
      resolvedAt: dsr.resolvedAt,
      resolvedByUserId: dsr.resolvedByUserId,
      createdAt: dsr.createdAt,
      updatedAt: dsr.updatedAt,
    });
  },
);

// ── PATCH /v1/data-subject-requests/:dsrId ───────────────────────────────────
// IO / security_administrator resolves or transitions a DSR.

const PatchDsrBody = z.object({
  status: z.enum(["in_progress", "completed", "rejected"]).optional(),
  resolutionNotes: z.string().max(4000).optional(),
});

router.patch(
  "/v1/data-subject-requests/:dsrId",
  requireSession,
  requireRole("popia_information_officer", "security_administrator"),
  async (req, res): Promise<void> => {
    const tenantId = req.session!.tenantId;
    const actorId = req.session!.userId;
    const dsrId = req.params.dsrId as string;

    const parsed = PatchDsrBody.safeParse(req.body);
    if (!parsed.success) {
      sendProblem(res, Problems.validationFailed(
        parsed.error.message,
        parsed.error.issues.map((i) => ({ field: i.path.join("."), code: i.code, message: i.message })),
      ));
      return;
    }

    if (Object.keys(parsed.data).length === 0) {
      sendProblem(res, Problems.validationFailed("Request body must contain at least one field to update"));
      return;
    }

    const now = new Date();
    const isTerminal = parsed.data.status === "completed" || parsed.data.status === "rejected";
    const extraFields = isTerminal
      ? { resolvedAt: now, resolvedByUserId: actorId }
      : {};

    const [updated] = await withTenantContext(tenantId, (tx) =>
      tx
        .update(dataSubjectRequestsTable)
        .set({ ...parsed.data, ...extraFields, updatedAt: now })
        .where(
          and(
            eq(dataSubjectRequestsTable.id, dsrId),
            eq(dataSubjectRequestsTable.tenantId, tenantId),
          ),
        )
        .returning(),
    );

    if (!updated) {
      sendProblem(res, Problems.notFound());
      return;
    }

    await writeAuditLog({
      tenantId,
      actorId,
      actorType: "user",
      action: "dsr.updated",
      targetType: "data_subject_request",
      targetId: dsrId,
      requestId: String(req.headers["x-request-id"] ?? ""),
      metadata: { status: updated.status, requestType: updated.requestType },
    });

    res.json({
      id: updated.id,
      userId: updated.userId,
      requestType: updated.requestType,
      status: updated.status,
      resolutionNotes: updated.resolutionNotes,
      resolvedAt: updated.resolvedAt,
      resolvedByUserId: updated.resolvedByUserId,
      updatedAt: updated.updatedAt,
    });
  },
);

export default router;
